<?php

namespace App\Core\Authorization\Events;

/**
 * Temporary security/domain event sink until Core/Audit ships.
 */
final class AuthorizationSecurityEvent
{
    public const USER_CREATED = 'USER_CREATED';

    public const USER_UPDATED = 'USER_UPDATED';

    public const USER_ENABLED = 'USER_ENABLED';

    public const USER_DISABLED = 'USER_DISABLED';

    public const USER_ROLES_CHANGED = 'USER_ROLES_CHANGED';

    public const ROLE_CREATED = 'ROLE_CREATED';

    public const ROLE_UPDATED = 'ROLE_UPDATED';

    public const ROLE_ACTIVATED = 'ROLE_ACTIVATED';

    public const ROLE_DEACTIVATED = 'ROLE_DEACTIVATED';

    public const ROLE_DELETED = 'ROLE_DELETED';

    public const ROLE_PERMISSIONS_CHANGED = 'ROLE_PERMISSIONS_CHANGED';

    public const PERMISSION_CATALOG_SYNCED = 'PERMISSION_CATALOG_SYNCED';

    public const ORGANIZATION_UNIT_CREATED = 'ORGANIZATION_UNIT_CREATED';

    public const ORGANIZATION_UNIT_UPDATED = 'ORGANIZATION_UNIT_UPDATED';

    public const ORGANIZATION_UNIT_MOVED = 'ORGANIZATION_UNIT_MOVED';

    public const ORGANIZATION_UNIT_ACTIVATED = 'ORGANIZATION_UNIT_ACTIVATED';

    public const ORGANIZATION_UNIT_DEACTIVATED = 'ORGANIZATION_UNIT_DEACTIVATED';

    public const ORGANIZATION_UNIT_DELETED = 'ORGANIZATION_UNIT_DELETED';

    public const ORGANIZATION_MANAGER_ASSIGNED = 'ORGANIZATION_MANAGER_ASSIGNED';

    public const EMPLOYEE_CREATED = 'EMPLOYEE_CREATED';

    public const EMPLOYEE_UPDATED = 'EMPLOYEE_UPDATED';

    public const EMPLOYEE_ACTIVATED = 'EMPLOYEE_ACTIVATED';

    public const EMPLOYEE_DEACTIVATED = 'EMPLOYEE_DEACTIVATED';

    public const EMPLOYEE_SUPERVISOR_CHANGED = 'EMPLOYEE_SUPERVISOR_CHANGED';

    public const EMPLOYEE_ORGANIZATION_CHANGED = 'EMPLOYEE_ORGANIZATION_CHANGED';

    public const EMPLOYEE_USER_LINKED = 'EMPLOYEE_USER_LINKED';

    public const EMPLOYEE_USER_UNLINKED = 'EMPLOYEE_USER_UNLINKED';

    public const POSITION_CREATED = 'POSITION_CREATED';

    public const POSITION_UPDATED = 'POSITION_UPDATED';

    public const POSITION_DELETED = 'POSITION_DELETED';

    public const CONTRACT_CREATED = 'CONTRACT_CREATED';

    public const CONTRACT_UPDATED = 'CONTRACT_UPDATED';

    public const CONTRACT_DELETED = 'CONTRACT_DELETED';

    public const CONTRACT_SUBMITTED_REVIEW = 'CONTRACT_SUBMITTED_REVIEW';

    public const CONTRACT_RETURNED_DRAFT = 'CONTRACT_RETURNED_DRAFT';

    public const CONTRACT_APPROVED = 'CONTRACT_APPROVED';

    public const CONTRACT_SIGNED = 'CONTRACT_SIGNED';

    public const CONTRACT_EXECUTED = 'CONTRACT_EXECUTED';

    public const CONTRACT_CLOSED = 'CONTRACT_CLOSED';

    public const CONTRACT_CANCELLED = 'CONTRACT_CANCELLED';

    public const CONTRACT_RENEWED = 'CONTRACT_RENEWED';

    public const CONTRACT_EXPIRED = 'CONTRACT_EXPIRED';

    public const CONTRACT_CATEGORY_CREATED = 'CONTRACT_CATEGORY_CREATED';

    public const CONTRACT_CATEGORY_UPDATED = 'CONTRACT_CATEGORY_UPDATED';

    public const CONTRACT_CATEGORY_ACTIVATED = 'CONTRACT_CATEGORY_ACTIVATED';

    public const CONTRACT_CATEGORY_DEACTIVATED = 'CONTRACT_CATEGORY_DEACTIVATED';

    public const CONTRACT_CATEGORY_DELETED = 'CONTRACT_CATEGORY_DELETED';

    public const MEETING_CREATED = 'MEETING_CREATED';

    public const MEETING_UPDATED = 'MEETING_UPDATED';

    public const MEETING_DELETED = 'MEETING_DELETED';

    public const MEETING_SCHEDULED = 'MEETING_SCHEDULED';

    public const MEETING_RESCHEDULED = 'MEETING_RESCHEDULED';

    public const MEETING_STARTED = 'MEETING_STARTED';

    public const MEETING_COMPLETED = 'MEETING_COMPLETED';

    public const MEETING_CANCELLED = 'MEETING_CANCELLED';

    public const MEETING_ATTENDEE_ADDED = 'MEETING_ATTENDEE_ADDED';

    public const MEETING_ATTENDEE_REMOVED = 'MEETING_ATTENDEE_REMOVED';

    public const MEETING_ATTENDANCE_UPDATED = 'MEETING_ATTENDANCE_UPDATED';

    public const MEETING_MINUTES_UPDATED = 'MEETING_MINUTES_UPDATED';

    public const MEETING_AGENDA_ITEM_CREATED = 'MEETING_AGENDA_ITEM_CREATED';

    public const MEETING_AGENDA_ITEM_UPDATED = 'MEETING_AGENDA_ITEM_UPDATED';

    public const MEETING_AGENDA_ITEM_DELETED = 'MEETING_AGENDA_ITEM_DELETED';

    public const MEETING_RECOMMENDATION_CREATED = 'MEETING_RECOMMENDATION_CREATED';

    public const MEETING_RECOMMENDATION_UPDATED = 'MEETING_RECOMMENDATION_UPDATED';

    public const MEETING_RECOMMENDATION_DELETED = 'MEETING_RECOMMENDATION_DELETED';

    public const DECISION_CREATED = 'DECISION_CREATED';

    public const DECISION_UPDATED = 'DECISION_UPDATED';

    public const DECISION_DELETED = 'DECISION_DELETED';

    public const DECISION_SUBMITTED = 'DECISION_SUBMITTED';

    public const DECISION_RETURNED_TO_DRAFT = 'DECISION_RETURNED_TO_DRAFT';

    public const DECISION_APPROVED = 'DECISION_APPROVED';

    public const DECISION_CANCELLED = 'DECISION_CANCELLED';

    public const DECISION_CLOSED = 'DECISION_CLOSED';

    public const TASK_CREATED = 'TASK_CREATED';

    public const TASK_UPDATED = 'TASK_UPDATED';

    public const TASK_ASSIGNED = 'TASK_ASSIGNED';

    public const TASK_REASSIGNED = 'TASK_REASSIGNED';

    public const TASK_STARTED = 'TASK_STARTED';

    public const TASK_PROGRESS_UPDATED = 'TASK_PROGRESS_UPDATED';

    public const TASK_COMPLETED = 'TASK_COMPLETED';

    public const TASK_CANCELLED = 'TASK_CANCELLED';

    public const TASK_DELETED = 'TASK_DELETED';

    public const DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED';

    public const DOCUMENT_UPDATED = 'DOCUMENT_UPDATED';

    public const DOCUMENT_LINKED = 'DOCUMENT_LINKED';

    public const DOCUMENT_UNLINKED = 'DOCUMENT_UNLINKED';

    public const DOCUMENT_DOWNLOADED = 'DOCUMENT_DOWNLOADED';

    public const DOCUMENT_ARCHIVED = 'DOCUMENT_ARCHIVED';

    public const DOCUMENT_RESTORED = 'DOCUMENT_RESTORED';

    public const DOCUMENT_DELETED = 'DOCUMENT_DELETED';

    public const DOCUMENT_CATEGORY_CREATED = 'DOCUMENT_CATEGORY_CREATED';

    public const DOCUMENT_CATEGORY_UPDATED = 'DOCUMENT_CATEGORY_UPDATED';

    public const DOCUMENT_CATEGORY_DELETED = 'DOCUMENT_CATEGORY_DELETED';

    public const WAREHOUSE_CREATED = 'WAREHOUSE_CREATED';

    public const WAREHOUSE_UPDATED = 'WAREHOUSE_UPDATED';

    public const WAREHOUSE_ACTIVATED = 'WAREHOUSE_ACTIVATED';

    public const WAREHOUSE_DEACTIVATED = 'WAREHOUSE_DEACTIVATED';

    public const WAREHOUSE_DELETED = 'WAREHOUSE_DELETED';

    public const INVENTORY_CATEGORY_CREATED = 'INVENTORY_CATEGORY_CREATED';

    public const INVENTORY_CATEGORY_UPDATED = 'INVENTORY_CATEGORY_UPDATED';

    public const INVENTORY_CATEGORY_DELETED = 'INVENTORY_CATEGORY_DELETED';

    public const INVENTORY_ITEM_CREATED = 'INVENTORY_ITEM_CREATED';

    public const INVENTORY_ITEM_UPDATED = 'INVENTORY_ITEM_UPDATED';

    public const INVENTORY_ITEM_ACTIVATED = 'INVENTORY_ITEM_ACTIVATED';

    public const INVENTORY_ITEM_DEACTIVATED = 'INVENTORY_ITEM_DEACTIVATED';

    public const INVENTORY_ITEM_DELETED = 'INVENTORY_ITEM_DELETED';

    public const STOCK_RECEIVED = 'STOCK_RECEIVED';

    public const STOCK_ISSUED = 'STOCK_ISSUED';

    public const STOCK_RETURNED = 'STOCK_RETURNED';

    public const STOCK_TRANSFERRED = 'STOCK_TRANSFERRED';

    public const STOCK_ADJUSTED = 'STOCK_ADJUSTED';

    /**
     * @param  array<string, mixed>  $context
     */
    public function __construct(
        public readonly string $name,
        public readonly array $context = [],
    ) {}
}
